name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.37.2"

      - name: Run fmt
        run: |
          deno task fmt:check

      - name: Run lint
        run: |
          deno task lint

      - name: Run type-check
        run: |
          deno task check
